### PR TITLE
ShadowOpacity, ShadowRadius and ShadowColor varying

### PR DESCRIPTION
**Pull request by DarthRamone**

### CODE REVIEW

**Comment by jdehlin** [comment]
Thanks for the PR. Could you set the defaults on your properties the same as they were set statically?

**Comment by DarthRamone** [comment]
Sorry :) That was just for testing and I forgot to change it back. Done.

**Comment by DarthRamone** [comment]
Please can you say, when it will be distributed to nuget?

**Comment by jdehlin** [comment]
@martijn00 owns the NuGet for this. I'll try to get it into the Xamarin Component in the next couple days.

**Comment by martijn00** [comment]
I can update the nuget for this!

Btw. @jdehlin i can easily add you to the nuget management for this so you can manage it as well.

**Comment by DarthRamone** [comment]
> I can update the nuget for this!

That would be awesome, thanks!

**Comment by DarthRamone** [comment]
@martijn00 Hello! Can I do anything to speed things up?

**Comment by martijn00** [comment]
New version is online: https://www.nuget.org/packages/SidebarNavigation/1.9.4
@DarthRamone @jdehlin

**Pull request merged**
