### PR TITLE
Adding EventHandler(Open/Close)

### PR DESCRIPTION
**Pull request by CitronMobile**
Adding an Event Handler to indicate that the state changed (Open/ Close)

### CODE REVIEW

**Comment by modplug** [comment]
I need this pull request as well :)

**Comment by jdehlin** [comment]
Somehow I completely missed this. I will get this merged in as soon as possible.

**Comment by jdehlin** [comment]
For some reason I wasn't able to get this to merge. I implemented the changes in master, though. Thanks for the pull request!

The component version has been submitted and is pending review.

**Comment by crejer** [comment]
Will you add this for unified too?

**Comment by jdehlin** [comment]
This should be added for both.

**Pull request closed without merging**
