### PR TITLE
Add new icon, and update readme to link to Nuget

### PR DESCRIPTION
**Pull request by martijn00**

### CODE REVIEW

**Comment by jdehlin** [comment]
Love the new icon! Can you have the url for the icon point to the one that will be merged into this repo?

**Comment by jdehlin** [comment]
Happy to see a Xamarin MVP interested in this library :)

Would you mind telling me a little about how you became an MVP?

**Comment by martijn00** [comment]
I've updated the URL to this repo!

**Comment by jdehlin** [comment]
Merged. Thanks! :+1:

**Comment by martijn00** [comment]
Join me for a chat on Slack to talk about other stuff: https://xamarinchat.herokuapp.com/ ;)

**Pull request merged**
